name: ref

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

env:
  ARCHIVE_LIBARCHIVE_REF_BUILD_FLAGS: "--cache-from plicease/libarchive-ref:0.00"

jobs:
  perl:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Build libarchive reference docker image
        run: ./maint/ref-build

      - name: Run symbols script
        run: ./maint/ref-symbols

      - name: Run update script
        run: ./maint/ref-update

      - name: Test oldest and latest
        run: ./maint/ref-test
